title: Apple vs tomato
hero_image: images/banner.png
description: Improve a classifier to give better results.
version: 4
listed: false
copyedit: false
last_tested: "2024-07-19"
steps:
  - title: What you will make
  - title: Create a model
    completion:
    - engaged
  - title: A different apple
  - title: Improve the model
    completion:
    - internal
  - title: What can you do now?
    completion:
    - external
