title: Apple vs tomato
hero_image: images/banner.png
description: Train a machine learning model to detect if you are holding an apple or a tomato, then improve it by including more diverse training data
version: 4
listed: false
copyedit: false
last_tested: "2024-07-19"
steps:
  - title: What you will make
  - title: Create a model
    completion:
    - engaged
  - title: Train and test
  - title: A different apple
  - title: Improve the model
    completion:
    - internal
  - title: What can you do now?
    completion:
    - external
