title: Apple vs tomato
hero_image: images/banner.png
description: Improve a classifier to give better results.
version: 4
listed: false
copyedit: false
last_tested: "2024-07-02"
steps:
  - title: What you will make
  - title: Test an existing model
    completion:
    - engaged
  - title: Improve the model
    completion:
    - internal
  - title: What can you do now?
    completion:
    - external
