title: Apple vs tomato
hero_image: images/banner.png
description: Hyfforddwch fodel dysgu peiriant i ganfod a ydych chi'n dal afal neu domato, yna ei wella trwy gynnwys data hyfforddi mwy amrywiol
version: 4
listed: true
copyedit: false
last_tested: "2024-07-19"
steps:
  - 
    title: Beth fyddwch chi'n ei wneud
  - 
    title: Creu model
    completion:
      - engaged
  - 
    title: Hyfforddi a phrofi
  - 
    title: Afal gwahanol
  - 
    title: Gwella'r model
    completion:
      - internal
  - 
    title: Beth allwch chi ei wneud nawr?
    completion:
      - external
