title: Apfel vs. Tomate
hero_image: images/banner.png
description: Trainiere ein Machine-Learning-Modell, um zu erkennen, ob du einen Apfel oder eine Tomate in der Hand hältst, und verbessere es anschließend durch die Einbeziehung umfangreicherer Trainingsdaten
version: 4
listed: true
copyedit: false
last_tested: "2024-07-19"
steps:
  - 
    title: Das wirst du machen
  - 
    title: Modell erstellen
    completion:
      - engaged
  - 
    title: Trainieren und testen
  - 
    title: Ein anderer Apfel
  - 
    title: Verbessere das Modell
    completion:
      - external
