title: Maçã vs tomate
hero_image: images/banner.png
description: Treine um modelo de aprendizado de máquina para detectar se você está segurando uma maçã ou um tomate e, em seguida, melhore-o incluindo dados de treinamento mais diversos
version: 4
listed: true
copyedit: false
last_tested: "2024-07-19"
steps:
  - 
    title: O que você vai fazer
  - 
    title: Crie um modelo
    completion:
      - engaged
  - 
    title: Treine e teste
  - 
    title: Uma maçã diferente
  - 
    title: Melhore o modelo
    completion:
      - internal
  - 
    title: O que você pode fazer agora?
    completion:
      - external
