title: تفاح أم طماطم
hero_image: images/banner.png
description: قم بتدريب نموذج التعلم الآلي لاكتشاف ما إذا كنت تحمل تفاحة أم طماطم، ثم قم بتحسينه من خلال تضمين بيانات تدريب أكثر تنوعًا
version: 4
listed: true
copyedit: false
last_tested: "2024-07-19"
steps:
  - 
    title: ماذا ستصنع
  - 
    title: إنشاء نموذج
    completion:
      - engaged
  - 
    title: درب واختبر
  - 
    title: تفاحة مختلفة
  - 
    title: حسن النموذج
    completion:
      - external
